### ISSUE TITLE
Release mutex anyway despite autocommit option

### ISSUE THREAD

**Issue by kafkiansky** [yiisoft/mutex#35]
Now every mutex driver must release mutex manually if option `autocommit` set on true.

This decision not only adds difficulties in implementing the new driver, but also does not eliminate problems when managing the mutex.

Imagine that you have some acquired mutex:

```php
$fileMutexFactory = new FileMutexFactory(__DIR__ . '/var/mutexes', false);

$mutex = $this->mutexes->create('some_mutex');

// some actions

$this->doSomething(); // But there will be exception

$mutex->release();
```

Such mutex will not be released because `autocommit` turn off.

I think, mutex releaser must be required and do not rely on the user's actions. Every mutex implementation **must** release mutex anyway in they destructor's.

The following code will guarantees that the mutex will be released anyway on the script shutdown, and it also does not require drivers to implement it themselves. 

```php
abstract class Mutex
{
       /**
     * Acquires a lock.
     *
     * @param int $timeout Time (in seconds) to wait for lock to be released. Defaults to zero meaning that method
     * will return false immediately in case lock was already acquired.
     */
    abstract public function acquire(int $timeout = 0): bool;

    /**
     * Releases a lock.
     */
    abstract public function release(): void;

    abstract public function released(): bool;

    final public function __destruct()
    {
       if (!$this->released()) {
           $this->release();
       }
    }
}
```

After that, we can delete the call to the `register_shutdown_function` function and the `autocommit' option.

**Comment by samdark** [comment]
The flag was removed. Having abstract class instead of an interface has its drawbacks.

**Comment by kafkiansky** [comment]
> The flag was removed. Having abstract class instead of an interface has its drawbacks.

You don't need an interface or an abstract class, but you go your own way as always.
