### ISSUE TITLE
Split specific drivers into their own packages

### ISSUE THREAD

**Issue by samdark** [yiisoft/mutex#6]
See https://forum.yiiframework.com/t/additional-packages-for-specific-drivers-storages/125718

- [x] [mutex-file](https://github.com/yiisoft/mutex-file)
- [x] [mutex-db-oracle](https://github.com/yiisoft/mutex-db-oracle)
- [x] [mutex-db-mysql](https://github.com/yiisoft/mutex-db-mysql)
- [x] [mutex-db-pgsql](https://github.com/yiisoft/mutex-db-pgsql)
- [x] [mutex-db-redis](https://github.com/yiisoft/mutex-db-redis)

**Comment by machour** [comment]
Could you create the repositories? I'll take care of this splitting as well

**Comment by samdark** [comment]
Done.

**Comment by machour** [comment]
We have a mutex implementations in Redis too:
 https://github.com/yiisoft/db-redis/blob/master/src/Mutex.php
Can you create `yiisoft/mutex-db-redis`?

There's also a mutex in `db-oracle` that I'm going to remove in favor of `mutex-db-oracle`.

Question: all db related mutex classes inherit from the abstract [DbMutex](https://github.com/yiisoft/mutex/blob/master/src/DbMutex.php) class. 

Does it make sense to create `mutex-db` package to host that class and require it from the other packages ? The class itself doesn't do much but enforce constructor parameters.

**Comment by samdark** [comment]
https://github.com/yiisoft/mutex-db-redis.

I don't think there's a need for general purpose mutex-db. It's OK to have different constructor signatures in these if needed.

**Comment by machour** [comment]
Done.

Notes:
 - Redis is incomplete: https://github.com/yiisoft/mutex-db-redis/issues/1
 - There are no tests written yet for mutex-db-xxx
